/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ucue.is.p3.RestaurantePorCapas.GUI;

import edu.ucue.is.p3.RestaurantePorCapas.MODEL.Cliente;
import edu.ucue.is.p3.RestaurantePorCapas.MODEL.Combo;
import edu.ucue.is.p3.RestaurantePorCapas.MODEL.Factura;
import edu.ucue.is.p3.RestaurantePorCapas.MODEL.Mesa;
import edu.ucue.is.p3.RestaurantePorCapas.MODEL.Pedido;
import edu.ucue.is.p3.RestaurantePorCapas.SRV.AtributoRequeridoException;
import edu.ucue.is.p3.RestaurantePorCapas.SRV.ClienteSRV;
import edu.ucue.is.p3.RestaurantePorCapas.SRV.ComboSRV;
import edu.ucue.is.p3.RestaurantePorCapas.SRV.MesaNoDisponibleException;
import edu.ucue.is.p3.RestaurantePorCapas.SRV.MesaSRV;
import edu.ucue.is.p3.RestaurantePorCapas.SRV.PedidoSRV;
import edu.ucue.is.p3.RestaurantePorCapas.SRV.PlatoSRV;
import edu.ucue.is.p3.RestaurantePorCapas.SRV.TablaNoSeleccionadaException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 3lys
 */
public class FormularioEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form FormularioEmpleado
     */
    private final PlatoSRV platoSVR = PlatoSRV.getInstancia();
    private final ComboSRV comboSRV = ComboSRV.getInstancia();
    private final PedidoSRV pedidoSRV = PedidoSRV.getInstancia();
    private final ClienteSRV clienteSRV = ClienteSRV.getInstancia();
    private LinkedList<Combo> combosDeCliente = new LinkedList<Combo>();
    private final MesaSRV mesaSRV = MesaSRV.getInstancia();

    private int filaSeleccionadaCombo = -1;
    DefaultTableModel tablaCombos;
    DefaultTableModel tablaPedidos;
    DefaultTableModel tablaCombosCliente;
    DefaultTableModel tablaFacturasClientes;

    public FormularioEmpleado() {
        initComponents();
        tablaCombos = (DefaultTableModel) combosjTable.getModel();
        tablaPedidos = (DefaultTableModel) pedidosjTable.getModel();
        tablaCombosCliente = (DefaultTableModel) combosClientejTable.getModel();
        tablaFacturasClientes = (DefaultTableModel) facturasClientesjTable.getModel();
        this.setResizable(true);
        this.setLocationRelativeTo(null);
        //this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        pedidosBTN = new javax.swing.JButton();
        facturaBTN = new javax.swing.JButton();
        salirBTN = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        facturasjInternalFrame = new javax.swing.JInternalFrame();
        jPanel15 = new javax.swing.JPanel();
        numero = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        cliente = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        facturajTable = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtsubtot = new javax.swing.JTextField();
        txtdes = new javax.swing.JTextField();
        txtiva = new javax.swing.JTextField();
        txttot = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        calcularFacturaBTN = new javax.swing.JButton();
        limpiarFacturaBTN = new javax.swing.JButton();
        imprimirFacturaBTN = new javax.swing.JButton();
        salirFacturaBTN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        facturasClientesjTable = new javax.swing.JTable();
        pedidosjInternalFrame = new javax.swing.JInternalFrame();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pNombreClienteTXT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        sNombreClienteTXT = new javax.swing.JTextField();
        sApellidoClienteTXT = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        pApellidoClienteTXT = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        cedulaClienteTXT = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        telefonoClienteTXT = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        combosClientejTable = new javax.swing.JTable();
        eliminarComboClienteBTN = new javax.swing.JButton();
        agregarComboClienteBTN = new javax.swing.JButton();
        direccionClienteTXT = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numeroMesaTXT = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        combosjTable = new javax.swing.JTable();
        jPanel22 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        pedidosjTable = new javax.swing.JTable();
        agregarPedidoBTN = new javax.swing.JButton();
        eliminarPedidoBTN = new javax.swing.JButton();
        modificarPedidoBTN = new javax.swing.JButton();
        salirPedidoBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setBackground(new java.awt.Color(102, 102, 102));
        jPanel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(null);

        jPanel11.setBackground(new java.awt.Color(153, 153, 153));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel11.setPreferredSize(new java.awt.Dimension(103, 4800));

        pedidosBTN.setBackground(new java.awt.Color(0, 0, 0));
        pedidosBTN.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        pedidosBTN.setForeground(new java.awt.Color(255, 255, 255));
        pedidosBTN.setText("Pedidos");
        pedidosBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));
        pedidosBTN.setFocusable(false);
        pedidosBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pedidosBTN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pedidosBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidosBTNActionPerformed(evt);
            }
        });

        facturaBTN.setBackground(new java.awt.Color(0, 0, 0));
        facturaBTN.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        facturaBTN.setForeground(new java.awt.Color(255, 255, 255));
        facturaBTN.setText("Facturas");
        facturaBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));
        facturaBTN.setFocusable(false);
        facturaBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        facturaBTN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        facturaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturaBTNActionPerformed(evt);
            }
        });

        salirBTN.setBackground(new java.awt.Color(0, 0, 0));
        salirBTN.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        salirBTN.setForeground(new java.awt.Color(255, 255, 255));
        salirBTN.setText("Salir");
        salirBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));
        salirBTN.setFocusable(false);
        salirBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salirBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(salirBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(facturaBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pedidosBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pedidosBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(facturaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salirBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(425, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel11);
        jPanel11.setBounds(13, 14, 120, 650);

        jPanel1.setLayout(null);

        facturasjInternalFrame.setBackground(new java.awt.Color(51, 51, 51));
        facturasjInternalFrame.setClosable(true);
        facturasjInternalFrame.setMaximizable(true);
        facturasjInternalFrame.setResizable(true);
        facturasjInternalFrame.setTitle("Factura");
        facturasjInternalFrame.setVisible(false);

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        numero.setEditable(false);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del Cliente"));

        jLabel5.setText("Fecha:");

        jLabel6.setText("Cliente:");

        jLabel7.setText("Dir. :");

        direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActionPerformed(evt);
            }
        });

        jLabel8.setText("RUC/CI:");

        jLabel11.setText("Telf:");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(direccion))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cedula)
                    .addComponent(telefono))
                .addGap(24, 24, 24))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Detalle"));

        facturajTable.setAutoCreateRowSorter(true);
        facturajTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cant", "Descripcion", "P. unit", "P. total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(facturajTable);
        if (facturajTable.getColumnModel().getColumnCount() > 0) {
            facturajTable.getColumnModel().getColumn(0).setMinWidth(50);
            facturajTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            facturajTable.getColumnModel().getColumn(0).setMaxWidth(50);
            facturajTable.getColumnModel().getColumn(2).setMinWidth(50);
            facturajTable.getColumnModel().getColumn(2).setPreferredWidth(50);
            facturajTable.getColumnModel().getColumn(2).setMaxWidth(50);
            facturajTable.getColumnModel().getColumn(3).setMinWidth(50);
            facturajTable.getColumnModel().getColumn(3).setPreferredWidth(50);
            facturajTable.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        jLabel12.setText("Subtotal:");

        jLabel13.setText("Descuento:");

        jLabel14.setText("IVA 0%");

        jLabel15.setText("Total:");

        txtsubtot.setEnabled(false);

        txtdes.setEnabled(false);

        txtiva.setEnabled(false);

        txttot.setEnabled(false);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtsubtot)
                    .addComponent(txtdes)
                    .addComponent(txtiva)
                    .addComponent(txttot, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addGap(36, 36, 36))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtsubtot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txttot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Factura N°");

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setText("RESTAURANTE");

        jLabel16.setText("RUC.: 0104530449001");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ucue/is/p3/RestaurantePorCapas/ICONOS/Anonymous_aiga_restaurant_bg.png"))); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel16)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(110, Short.MAX_VALUE))))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13))))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))))
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(51, 51, 51)));

        calcularFacturaBTN.setText("Calcular");

        limpiarFacturaBTN.setText("Limpiar");
        limpiarFacturaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarFacturaBTNActionPerformed(evt);
            }
        });

        imprimirFacturaBTN.setText("Imprimir");

        salirFacturaBTN.setText("Salir");
        salirFacturaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirFacturaBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(calcularFacturaBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(imprimirFacturaBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(salirFacturaBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(limpiarFacturaBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(calcularFacturaBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(limpiarFacturaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imprimirFacturaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(salirFacturaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Lista De Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        facturasClientesjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Cedula", "Direccion", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        facturasClientesjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facturasClientesjTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(facturasClientesjTable);
        if (facturasClientesjTable.getColumnModel().getColumnCount() > 0) {
            facturasClientesjTable.getColumnModel().getColumn(1).setMinWidth(85);
            facturasClientesjTable.getColumnModel().getColumn(1).setPreferredWidth(85);
            facturasClientesjTable.getColumnModel().getColumn(1).setMaxWidth(85);
            facturasClientesjTable.getColumnModel().getColumn(2).setMinWidth(85);
            facturasClientesjTable.getColumnModel().getColumn(2).setPreferredWidth(85);
            facturasClientesjTable.getColumnModel().getColumn(2).setMaxWidth(85);
            facturasClientesjTable.getColumnModel().getColumn(3).setMinWidth(85);
            facturasClientesjTable.getColumnModel().getColumn(3).setPreferredWidth(85);
            facturasClientesjTable.getColumnModel().getColumn(3).setMaxWidth(85);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout facturasjInternalFrameLayout = new javax.swing.GroupLayout(facturasjInternalFrame.getContentPane());
        facturasjInternalFrame.getContentPane().setLayout(facturasjInternalFrameLayout);
        facturasjInternalFrameLayout.setHorizontalGroup(
            facturasjInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facturasjInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        facturasjInternalFrameLayout.setVerticalGroup(
            facturasjInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facturasjInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facturasjInternalFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
            .addGroup(facturasjInternalFrameLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(facturasjInternalFrame);
        facturasjInternalFrame.setBounds(20, 10, 1140, 637);

        pedidosjInternalFrame.setClosable(true);
        pedidosjInternalFrame.setMaximizable(true);
        pedidosjInternalFrame.setResizable(true);
        pedidosjInternalFrame.setTitle("Pedido");
        pedidosjInternalFrame.setVisible(false);

        jPanel27.setBackground(new java.awt.Color(153, 153, 153));
        jPanel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel27.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N

        jPanel28.setBackground(new java.awt.Color(204, 204, 204));
        jPanel28.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos Personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, null, java.awt.Color.white));
        jPanel28.setForeground(new java.awt.Color(204, 204, 204));

        jLabel9.setText("Primer nombre :");

        pNombreClienteTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNombreClienteTXTActionPerformed(evt);
            }
        });

        jLabel10.setText("Segundo nombre :");

        jLabel18.setText("Segundo apellido :");

        pApellidoClienteTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pApellidoClienteTXTActionPerformed(evt);
            }
        });

        jLabel19.setText("Primer apellido :");

        jLabel48.setText("Cédula :");

        cedulaClienteTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaClienteTXTActionPerformed(evt);
            }
        });
        cedulaClienteTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cedulaClienteTXTKeyTyped(evt);
            }
        });

        jLabel49.setText("Teléfono :");

        telefonoClienteTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoClienteTXTActionPerformed(evt);
            }
        });
        telefonoClienteTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoClienteTXTKeyTyped(evt);
            }
        });

        jLabel50.setText("Dirección :");

        jLabel51.setBackground(new java.awt.Color(255, 255, 255));
        jLabel51.setForeground(new java.awt.Color(255, 0, 0));
        jLabel51.setText("*");

        jLabel52.setForeground(new java.awt.Color(255, 0, 0));
        jLabel52.setText("*");

        jLabel53.setForeground(new java.awt.Color(255, 0, 0));
        jLabel53.setText("*");

        jLabel57.setForeground(new java.awt.Color(255, 0, 0));
        jLabel57.setText("*");

        jLabel58.setForeground(new java.awt.Color(255, 0, 0));
        jLabel58.setText("*");

        jLabel60.setForeground(new java.awt.Color(255, 0, 0));
        jLabel60.setText("*");

        combosClientejTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        combosClientejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Primer plato", "Segundo plato", "Bebida", "Extra", "Precio Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(combosClientejTable);
        if (combosClientejTable.getColumnModel().getColumnCount() > 0) {
            combosClientejTable.getColumnModel().getColumn(0).setMinWidth(40);
            combosClientejTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            combosClientejTable.getColumnModel().getColumn(0).setMaxWidth(40);
            combosClientejTable.getColumnModel().getColumn(5).setMinWidth(75);
            combosClientejTable.getColumnModel().getColumn(5).setPreferredWidth(75);
            combosClientejTable.getColumnModel().getColumn(5).setMaxWidth(75);
        }

        eliminarComboClienteBTN.setText("Eliminar combo");
        eliminarComboClienteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarComboClienteBTNActionPerformed(evt);
            }
        });

        agregarComboClienteBTN.setText("Agregar combo");
        agregarComboClienteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarComboClienteBTNActionPerformed(evt);
            }
        });

        jLabel61.setForeground(new java.awt.Color(255, 0, 0));
        jLabel61.setText("*");

        jLabel3.setText("N° mesa :");

        numeroMesaTXT.setText("0");
        numeroMesaTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroMesaTXTActionPerformed(evt);
            }
        });
        numeroMesaTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroMesaTXTKeyTyped(evt);
            }
        });

        jLabel54.setForeground(new java.awt.Color(255, 0, 0));
        jLabel54.setText("*");

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cedulaClienteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(jLabel49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefonoClienteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel28Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pNombreClienteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel28Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pApellidoClienteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sApellidoClienteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sNombreClienteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addComponent(jLabel50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(direccionClienteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroMesaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(agregarComboClienteBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(eliminarComboClienteBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane3)
            .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                    .addContainerGap(606, Short.MAX_VALUE)
                    .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(296, 296, 296)))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(agregarComboClienteBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarComboClienteBTN))
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel28Layout.createSequentialGroup()
                                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(pNombreClienteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel51))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(pApellidoClienteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel53)))
                            .addGroup(jPanel28Layout.createSequentialGroup()
                                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(sNombreClienteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel52))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(sApellidoClienteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel57))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel48)
                            .addComponent(cedulaClienteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel49)
                            .addComponent(telefonoClienteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel58))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel50)
                            .addComponent(direccionClienteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel60)
                            .addComponent(jLabel3)
                            .addComponent(numeroMesaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel54))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
            .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel28Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(jLabel61)
                    .addContainerGap(125, Short.MAX_VALUE)))
        );

        jPanel30.setBackground(new java.awt.Color(204, 204, 204));
        jPanel30.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 153, 153)), "Lista de combos registrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(0, 153, 153)));
        jPanel30.setForeground(new java.awt.Color(204, 204, 204));

        combosjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Primer Plato", "Segundo Plato", "Bebida", "Extra", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        combosjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combosjTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(combosjTable);
        if (combosjTable.getColumnModel().getColumnCount() > 0) {
            combosjTable.getColumnModel().getColumn(0).setMinWidth(50);
            combosjTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            combosjTable.getColumnModel().getColumn(0).setMaxWidth(50);
            combosjTable.getColumnModel().getColumn(5).setMinWidth(75);
            combosjTable.getColumnModel().getColumn(5).setPreferredWidth(75);
            combosjTable.getColumnModel().getColumn(5).setMaxWidth(75);
        }

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel22.setBackground(new java.awt.Color(204, 204, 204));
        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Lista de pedidos registrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(0, 153, 153)));

        pedidosjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Cliente", "Cédula", "Dirección", "Teléfono", "Pedidos", "Precio", "Mesa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(pedidosjTable);
        if (pedidosjTable.getColumnModel().getColumnCount() > 0) {
            pedidosjTable.getColumnModel().getColumn(0).setMinWidth(40);
            pedidosjTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            pedidosjTable.getColumnModel().getColumn(0).setMaxWidth(40);
            pedidosjTable.getColumnModel().getColumn(6).setMinWidth(75);
            pedidosjTable.getColumnModel().getColumn(6).setPreferredWidth(75);
            pedidosjTable.getColumnModel().getColumn(6).setMaxWidth(75);
            pedidosjTable.getColumnModel().getColumn(7).setMinWidth(50);
            pedidosjTable.getColumnModel().getColumn(7).setPreferredWidth(50);
            pedidosjTable.getColumnModel().getColumn(7).setMaxWidth(50);
        }

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        agregarPedidoBTN.setText("Agregar");
        agregarPedidoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPedidoBTNActionPerformed(evt);
            }
        });

        eliminarPedidoBTN.setText("Eliminar");
        eliminarPedidoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPedidoBTNActionPerformed(evt);
            }
        });

        modificarPedidoBTN.setText("Modificar");
        modificarPedidoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarPedidoBTNActionPerformed(evt);
            }
        });

        salirPedidoBTN.setText("Salir");
        salirPedidoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirPedidoBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eliminarPedidoBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modificarPedidoBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salirPedidoBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agregarPedidoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5))
                    .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addComponent(agregarPedidoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eliminarPedidoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modificarPedidoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salirPedidoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pedidosjInternalFrameLayout = new javax.swing.GroupLayout(pedidosjInternalFrame.getContentPane());
        pedidosjInternalFrame.getContentPane().setLayout(pedidosjInternalFrameLayout);
        pedidosjInternalFrameLayout.setHorizontalGroup(
            pedidosjInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pedidosjInternalFrameLayout.createSequentialGroup()
                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pedidosjInternalFrameLayout.setVerticalGroup(
            pedidosjInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pedidosjInternalFrameLayout.createSequentialGroup()
                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(pedidosjInternalFrame);
        pedidosjInternalFrame.setBounds(10, 10, 1144, 590);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ucue/is/p3/RestaurantePorCapas/ICONOS/Punisher.jpg"))); // NOI18N
        jLabel1.setText("   ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1190, 650);

        jPanel10.add(jPanel1);
        jPanel1.setBounds(143, 14, 1190, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 1340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void pedidosBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidosBTNActionPerformed
        facturasjInternalFrame.setVisible(false);
        pedidosjInternalFrame.setVisible(true);
        cargarTablasConDatosPedidos();
    }//GEN-LAST:event_pedidosBTNActionPerformed

    private void salirBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBTNActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_salirBTNActionPerformed

    private void combosjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combosjTableMouseClicked
        int filaSelect = combosjTable.getSelectedRow();
        filaSeleccionadaCombo = filaSelect;
    }//GEN-LAST:event_combosjTableMouseClicked

    private void eliminarPedidoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPedidoBTNActionPerformed
        try {
            int filaSelect = pedidosjTable.getSelectedRow();
            String cedula = pedidosjTable.getValueAt(filaSelect, 2).toString();
            tablaPedidos.removeRow(filaSelect);
            pedidoSRV.eliminarPedido(pedidoSRV.buscarPedido(cedula));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No seleccionó ninguna fila");
        } finally {
            limpiarSelecciones();
            cargarTablasConDatosPedidos();
        }
    }//GEN-LAST:event_eliminarPedidoBTNActionPerformed

    private void modificarPedidoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarPedidoBTNActionPerformed
        if (filaSeleccionadaCombo == -1) {
            JOptionPane.showMessageDialog(null, "No seleciono fila");
        }
        if (filaSeleccionadaCombo >= 0) {
//            String p = principalComboTXT.getText();
//            String s = segundoComboTXT.getText();
//            String b = bebidaComboTXT.getText();
//            String e = extraComboTXT.getText();
//            String contador = numeroComboTXT.getText();
//            String precio = "5.6";
//            String datos[] = {contador, p, s, b, e, precio};
//            comboSRV.modificarCombo(comboSRV.listaCombos().get(filaSeleccionadaCombo), contador, precio, platoSRV.buscarPlatoPrincipal(p), platoSRV.buscarPlatoSecundario(s), platoSRV.buscarBebida(b), platoSRV.buscarPostre(e));
            //           for (int i = 0; i < tablaCombos.getColumnCount(); i++) {
//                tablaCombos.setValueAt(datos[i], filaSeleccionadaCombo, i);
//            }
            //this.combosjTable.setModel(tablaCombos);
        }

    }//GEN-LAST:event_modificarPedidoBTNActionPerformed

    private void salirPedidoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirPedidoBTNActionPerformed
        pedidosjInternalFrame.setVisible(false);

    }//GEN-LAST:event_salirPedidoBTNActionPerformed

    private void agregarPedidoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPedidoBTNActionPerformed
        try {
            String primNom = pNombreClienteTXT.getText();
            String segNom = sNombreClienteTXT.getText();
            String primApe = pApellidoClienteTXT.getText();
            String segApe = sApellidoClienteTXT.getText();
            String direc = direccionClienteTXT.getText();
            String cedula = cedulaClienteTXT.getText();
            String telefono = telefonoClienteTXT.getText();
            String numMesa = numeroMesaTXT.getText();
            Factura factura = new Factura(23.24, 23.34, 2.3, 004);
            Cliente cliente = new Cliente(primNom, segNom, primApe, segApe, cedula, telefono, direc, combosDeCliente, factura);
            pedidoSRV.insertarPedido(cliente, mesaSRV.buscarMesa(Integer.parseInt(numMesa)));
            limpiarDatosDeCliente();
            combosDeCliente.removeAll(combosDeCliente);
        } catch (AtributoRequeridoException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        } catch (MesaNoDisponibleException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        } finally {
            cargarTablasConDatosPedidos();
        }
    }//GEN-LAST:event_agregarPedidoBTNActionPerformed

    private void facturaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturaBTNActionPerformed
        facturasjInternalFrame.setVisible(true);
        pedidosjInternalFrame.setVisible(false);
        cargarTablasConDatosFactura();
    }//GEN-LAST:event_facturaBTNActionPerformed

    private void pNombreClienteTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNombreClienteTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pNombreClienteTXTActionPerformed

    private void pApellidoClienteTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pApellidoClienteTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pApellidoClienteTXTActionPerformed

    private void telefonoClienteTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoClienteTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoClienteTXTActionPerformed

    private void eliminarComboClienteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarComboClienteBTNActionPerformed
        try {
            int filaSelect = combosClientejTable.getSelectedRow();
            String numCom = combosClientejTable.getValueAt(filaSelect, 0).toString();
            tablaCombosCliente.removeRow(filaSelect);
            combosDeCliente.remove(comboSRV.buscarCombo(numCom));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No seleccionó ninguna fila");
        } finally {
            limpiarSelecciones();
        }
    }//GEN-LAST:event_eliminarComboClienteBTNActionPerformed

    private void agregarComboClienteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarComboClienteBTNActionPerformed
        try {
            int filaSelect = combosjTable.getSelectedRow();
            String numCom = combosjTable.getValueAt(filaSelect, 0).toString();
            String prim = combosjTable.getValueAt(filaSelect, 1).toString();
            String seg = combosjTable.getValueAt(filaSelect, 2).toString();
            String beb = combosjTable.getValueAt(filaSelect, 3).toString();
            String ext = combosjTable.getValueAt(filaSelect, 4).toString();
            String pre = combosjTable.getValueAt(filaSelect, 5).toString();
            String precio = "5.6";
            String datos[] = {numCom, prim, seg, beb, ext, pre};
            tablaCombosCliente.addRow(datos);
            combosDeCliente.add(comboSRV.buscarCombo(numCom));
            limpiarSelecciones();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No seleccionó ninguna fila");
        }

    }//GEN-LAST:event_agregarComboClienteBTNActionPerformed

    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionActionPerformed

    private void limpiarFacturaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarFacturaBTNActionPerformed
        //limpiar
        cliente.setText("");
        direccion.setText("");
        cedula.setText(null);
        telefono.setText(null);
        txtsubtot.setText(null);
        txtdes.setText(null);
        txtiva.setText(null);
        txttot.setText(null);
        //si esq usas este para limpiar la tabla le limpias segun el arreglo q le hayas hecho

        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarFacturaBTNActionPerformed

    private void salirFacturaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirFacturaBTNActionPerformed
        facturasjInternalFrame.setVisible(false);
    }//GEN-LAST:event_salirFacturaBTNActionPerformed

    private void numeroMesaTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroMesaTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroMesaTXTActionPerformed

    private void numeroMesaTXTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroMesaTXTKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
        int k = (int) evt.getKeyChar();
        if (numeroMesaTXT.getText().length() >= 20) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
            JOptionPane.showMessageDialog(null, "Ha excedido el número máximo de caracteres!!! (20)", "Validando Datos",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_numeroMesaTXTKeyTyped

    private void cedulaClienteTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaClienteTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaClienteTXTActionPerformed

    private void cedulaClienteTXTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedulaClienteTXTKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
        int k = (int) evt.getKeyChar();
        if (cedulaClienteTXT.getText().length() >= 10) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
            JOptionPane.showMessageDialog(null, "Ha excedido el número máximo de numeros ", "Validando Datos",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cedulaClienteTXTKeyTyped

    private void telefonoClienteTXTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoClienteTXTKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
        int k = (int) evt.getKeyChar();
        if (telefonoClienteTXT.getText().length() >= 10) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
            JOptionPane.showMessageDialog(null, "Ha excedido el número máximo de numeros ", "Validando Datos",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_telefonoClienteTXTKeyTyped

    private void facturasClientesjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facturasClientesjTableMouseClicked
        try {
            int filaSelect = facturasClientesjTable.getSelectedRow();
            String cedulaBuscar = facturasClientesjTable.getValueAt(filaSelect, 1).toString();
            Pedido pedido = pedidoSRV.buscarPedido(cedulaBuscar);
            cliente.setText(pedido.getCliente().getpNombre() + " " + pedido.getCliente().getsNombre() + " " + pedido.getCliente().getpApellido() + " " + pedido.getCliente().getsApellido());
            fecha.setText(fechaActual());
            direccion.setText(pedido.getCliente().getDireccion());
            cedula.setText(pedido.getCliente().getCedula());
            telefono.setText(pedido.getCliente().getTelefono());
            numero.setText(Integer.toString(pedido.getFactura().getNumeroFactura()));
            for (int i = 0; i < pedido.getCliente().getCombosDeCliente().size(); i++) {
                
            }
        } catch (Exception e) {
        }

        limpiarSelecciones();
    }//GEN-LAST:event_facturasClientesjTableMouseClicked
    public static String fechaActual() {
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatoFecha.format(fecha);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarComboClienteBTN;
    private javax.swing.JButton agregarPedidoBTN;
    private javax.swing.JButton calcularFacturaBTN;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField cedulaClienteTXT;
    private javax.swing.JTextField cliente;
    private javax.swing.JTable combosClientejTable;
    private javax.swing.JTable combosjTable;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField direccionClienteTXT;
    private javax.swing.JButton eliminarComboClienteBTN;
    private javax.swing.JButton eliminarPedidoBTN;
    private javax.swing.JButton facturaBTN;
    private javax.swing.JTable facturajTable;
    private javax.swing.JTable facturasClientesjTable;
    private javax.swing.JInternalFrame facturasjInternalFrame;
    private javax.swing.JTextField fecha;
    private javax.swing.JButton imprimirFacturaBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton limpiarFacturaBTN;
    private javax.swing.JButton modificarPedidoBTN;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField numeroMesaTXT;
    private javax.swing.JTextField pApellidoClienteTXT;
    private javax.swing.JTextField pNombreClienteTXT;
    private javax.swing.JButton pedidosBTN;
    private javax.swing.JInternalFrame pedidosjInternalFrame;
    private javax.swing.JTable pedidosjTable;
    private javax.swing.JTextField sApellidoClienteTXT;
    private javax.swing.JTextField sNombreClienteTXT;
    private javax.swing.JButton salirBTN;
    private javax.swing.JButton salirFacturaBTN;
    private javax.swing.JButton salirPedidoBTN;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField telefonoClienteTXT;
    private javax.swing.JTextField txtdes;
    private javax.swing.JTextField txtiva;
    private javax.swing.JTextField txtsubtot;
    private javax.swing.JTextField txttot;
    // End of variables declaration//GEN-END:variables

    private void cargarTablasConDatosPedidos() {
        for (int i = combosjTable.getRowCount() - 1; i >= 0; i--) {
            tablaCombos.removeRow(i);
        }
        for (int i = 0; i < comboSRV.listaCombos().size(); i++) {
            String descripcion = "";
            String principal = "";
            String segundo = "";
            String bebida = "";
            String postre = "";
            String precio = "";
            if (comboSRV.listaCombos().get(i) != null) {
                descripcion = comboSRV.listaCombos().get(i).getDescripcion();
            }
            if (comboSRV.listaCombos().get(i).getPrincipal() != null) {
                principal = comboSRV.listaCombos().get(i).getPrincipal().getDescripcion();
            }
            if (comboSRV.listaCombos().get(i).getSegundo() != null) {
                segundo = comboSRV.listaCombos().get(i).getSegundo().getDescripcion();
            }
            if (comboSRV.listaCombos().get(i).getBebida() != null) {
                bebida = comboSRV.listaCombos().get(i).getBebida().getDescripcion();
            }
            if (comboSRV.listaCombos().get(i).getPostre() != null) {
                postre = comboSRV.listaCombos().get(i).getPostre().getDescripcion();
            }
            if (comboSRV.listaCombos().get(i).getPrecio() != null) {
                precio = comboSRV.listaCombos().get(i).getPrecio();
            }
            String datos[] = {descripcion, principal, segundo, bebida, postre, precio};
            tablaCombos.addRow(datos);
        }
//        combosDeCliente.removeAll(combosDeCliente);

        combosjTable.clearSelection();
        for (int i = pedidosjTable.getRowCount() - 1; i >= 0; i--) {
            tablaPedidos.removeRow(i);
        }
        for (int i = 0; i < pedidoSRV.listaPedidos().size(); i++) {
            String nombre = pedidoSRV.listaPedidos().get(i).getCliente().getpNombre() + " " + pedidoSRV.listaPedidos().get(i).getCliente().getsNombre() + " " + pedidoSRV.listaPedidos().get(i).getCliente().getpApellido() + " " + pedidoSRV.listaPedidos().get(i).getCliente().getsApellido();
            String cedula = pedidoSRV.listaPedidos().get(i).getCliente().getCedula();
            String direccion = pedidoSRV.listaPedidos().get(i).getCliente().getDireccion();
            String telefono = pedidoSRV.listaPedidos().get(i).getCliente().getTelefono();
            double precio = 2.3;//pedidoSRV.listaPedidos().get(i).getFactura().getTotal();
            int mesa = pedidoSRV.listaPedidos().get(i).getMesa().getNumeroMesa();
            int pedidos = pedidoSRV.listaPedidos().size();
            String datos[] = {Integer.toString(i), nombre, cedula, direccion, telefono, Integer.toString(pedidos), Double.toString(precio), Integer.toString(mesa)};
            tablaPedidos.addRow(datos);
        }

        //   combosjTable.setModel(tablaCombos);
    }

    private void limpiarSelecciones() {
        combosClientejTable.clearSelection();
        combosjTable.clearSelection();
        pedidosjTable.clearSelection();
    }

    public void limpiarDatosDeCliente() {
        pApellidoClienteTXT.setText("");
        pNombreClienteTXT.setText("");
        sApellidoClienteTXT.setText("");
        sNombreClienteTXT.setText("");
        direccionClienteTXT.setText("");
        cedulaClienteTXT.setText("");
        telefonoClienteTXT.setText("");
        numeroMesaTXT.setText("0");
        for (int i = combosClientejTable.getRowCount() - 1; i >= 0; i--) {
            tablaCombosCliente.removeRow(i);
        }
    }

    private void cargarTablasConDatosFactura() {
        facturasClientesjTable.clearSelection();
        for (int i = facturasClientesjTable.getRowCount() - 1; i >= 0; i--) {
            tablaFacturasClientes.removeRow(i);
        }
        for (int i = 0; i < pedidoSRV.listaPedidos().size(); i++) {
            String nombre = pedidoSRV.listaPedidos().get(i).getCliente().getpNombre() + " " + pedidoSRV.listaPedidos().get(i).getCliente().getsNombre() + " " + pedidoSRV.listaPedidos().get(i).getCliente().getpApellido() + " " + pedidoSRV.listaPedidos().get(i).getCliente().getsApellido();
            String cedula = pedidoSRV.listaPedidos().get(i).getCliente().getCedula();
            String direccion = pedidoSRV.listaPedidos().get(i).getCliente().getDireccion();
            String telefono = pedidoSRV.listaPedidos().get(i).getCliente().getTelefono();
            String datos[] = {nombre, cedula, direccion, telefono};
            tablaFacturasClientes.addRow(datos);
        }

    }
}
