/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ucue.is.p3.RestaurantePorCapas.GUI;

import edu.ucue.is.p3.RestaurantePorCapas.SRV.MesaSRV;
import edu.ucue.is.p3.RestaurantePorCapas.SRV.PlatoSRV;
import edu.ucue.is.p3.RestaurantePorCapas.DAO.*;
import edu.ucue.is.p3.RestaurantePorCapas.MODEL.Pedido;
import edu.ucue.is.p3.RestaurantePorCapas.SRV.ComboSRV;
import edu.ucue.is.p3.RestaurantePorCapas.SRV.PedidoSRV;

/**
 *
 * @author 3lys
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private PlatoSRV platoSRV = new PlatoSRV();
    private MesaSRV mesaSRV = new MesaSRV();
    private PedidoSRV pedidoSRV = new PedidoSRV();
    private ComboSRV comboSRV= new ComboSRV();

    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        platoSRV.cargarDatos();
        mesaSRV.cargarDatos();
        comboSRV.cargarDatos();
        pedidoSRV.cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        aceptarIngEmpBTN = new javax.swing.JButton();
        aceptarIngAdmBTN = new javax.swing.JButton();
        salirBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);

        aceptarIngEmpBTN.setText("Empleado");
        aceptarIngEmpBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aceptarIngEmpBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarIngEmpBTNActionPerformed(evt);
            }
        });
        jPanel2.add(aceptarIngEmpBTN);
        aceptarIngEmpBTN.setBounds(0, 430, 410, 50);

        aceptarIngAdmBTN.setText("Administrador");
        aceptarIngAdmBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aceptarIngAdmBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarIngAdmBTNActionPerformed(evt);
            }
        });
        jPanel2.add(aceptarIngAdmBTN);
        aceptarIngAdmBTN.setBounds(410, 430, 407, 50);

        salirBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ucue/is/p3/RestaurantePorCapas/ICONOS/logout.png"))); // NOI18N
        salirBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salirBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBTNActionPerformed(evt);
            }
        });
        jPanel2.add(salirBTN);
        salirBTN.setBounds(820, 430, 48, 51);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ucue/is/p3/RestaurantePorCapas/ICONOS/Principal.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, -10, 870, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ucue/is/p3/RestaurantePorCapas/ICONOS/fondo-pantalla.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 870, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarIngEmpBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarIngEmpBTNActionPerformed
        // TODO add your handling code here:
        IngresoEmpleado ventanaIngresoEmpleado = new IngresoEmpleado();
        ventanaIngresoEmpleado.setVisible(true);
    }//GEN-LAST:event_aceptarIngEmpBTNActionPerformed

    private void aceptarIngAdmBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarIngAdmBTNActionPerformed
        // TODO add your handling code here:
        IngresoAdministrador ventanaIngredoAdministrador = new IngresoAdministrador();
        ventanaIngredoAdministrador.setVisible(true);
    }//GEN-LAST:event_aceptarIngAdmBTNActionPerformed

    private void salirBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_salirBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarIngAdmBTN;
    private javax.swing.JButton aceptarIngEmpBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton salirBTN;
    // End of variables declaration//GEN-END:variables
}
